DROP TABLE IF EXISTS ticktrack_logs;

CREATE TABLE ticktrack_logs(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER 
        REFERENCES ticktrack_users(id) ON DELETE CASCADE NOT NULL,
    date_created DATE DEFAULT CURRENT_DATE,
    date_modified DATE DEFAULT CURRENT_DATE,
    general_health_id INTEGER 
        REFERENCES ticktrack_generalhealth(id)
    
);