INSERT INTO ticktrack_symptoms (symptom)
VALUES
('Persistent swollen glands'),
('Sore throat'),
('Fevers'),
('Sore soles, especially in AM'),
('Joint pain'),
('Joint swelling'),
('Unexplained back pain'),
('Stiffness of the joints or back'),
('Muscle pain or cramps'),
('Obvious muscle weakness'),
('Twitching of the face or other muscles'),
('Confusion, difficulty thinking'),
('Difficulty concentrating, reading, or absorbing new information'),
('Word search, name block'),
('Forgetfulness, poor short term memory, poor attention'),
('Disorientation: getting lost, going wrong places'),
('Speech errors - wrong word, misspeaking'),
('Mood swings, irritability, depression'),
('Anxiety, panic attacks'),
('Psychosis (hallucinations, delusions, paranoia, bipolar'),
('Tremor'),
('Seizures'),
('Headache'),
('Light sensitivity'),
('Vision: double, blurry, floaters'),
('Ear pain'),
('Hearing: buzzing, ringing, decreased hearing'),
('Increased motion sickness, vertigo, spinning'),
('Off balance, "tippy" feeling'),
('Lighheadedness, wooziness, unavoidable need to sit or lie down'),
('Tingling, numbness, burning, or stabbing sensations, shooting pains, skin hypersensitivity'),
('Facial paralysis - Bells Palsy'),
('Neck creaks and cracks, stiffness, neck pain'),
('Fatigue, tired, poor stamina'),
('Insomnia, fractionated sleep, early awakening'),
('Excessive night time sleep'),
('Napping during the day'),
('Unexplained weight change'),
('Unexplained hair loss'),
('Pain in genital area'),
('Unexplained menstrual irregularity'),
('Unexplained milk production; breast pain'),
('Irritable bladder or bladder dysfunction'),
('Erectile dysfunction'),
('Loss of libido'),
('Queasy stomach or nausea'),
('Heartburn, stomach pain'),
('Constipation'),
('Diarrhea'),
('Low abdominal pain, cramps'),
('Heart murmur or valve prolapse'),
('Heart palpitations, pulse skips'),
('"Heart block" on EKG'),
('Chest wall pain or sore ribs'),
('Head congestion'),
('Breathlessness, "air hunger", unexplained chronic cough'),
('Night sweats'),
('Exaggerated symptoms or worse hangover from alcohol'),
('Symptoms flare every four weeks'),
('Degree of disability');